INSERT INTO `ao_professions` (`aoProfID`, `aoDBProfID`, `aoProf`, `aoIconID`) VALUES (1, 9, 'Enforcer', 117926);
INSERT INTO `ao_professions` (`aoProfID`, `aoDBProfID`, `aoProf`, `aoIconID`) VALUES (2, 12, 'Meta-Physicist', 16308);
INSERT INTO `ao_professions` (`aoProfID`, `aoDBProfID`, `aoProf`, `aoIconID`) VALUES (3, 6, 'Adventurer', 84203);
INSERT INTO `ao_professions` (`aoProfID`, `aoDBProfID`, `aoProf`, `aoIconID`) VALUES (4, 14, 'Keeper', 38911);
INSERT INTO `ao_professions` (`aoProfID`, `aoDBProfID`, `aoProf`, `aoIconID`) VALUES (5, 15, 'Shade', 39290);
INSERT INTO `ao_professions` (`aoProfID`, `aoDBProfID`, `aoProf`, `aoIconID`) VALUES (6, 1, 'Soldier', 301604);
INSERT INTO `ao_professions` (`aoProfID`, `aoDBProfID`, `aoProf`, `aoIconID`) VALUES (7, 11, 'Nano-Technician', 45190);
INSERT INTO `ao_professions` (`aoProfID`, `aoDBProfID`, `aoProf`, `aoIconID`) VALUES (8, 7, 'Trader', 117993);
INSERT INTO `ao_professions` (`aoProfID`, `aoDBProfID`, `aoProf`, `aoIconID`) VALUES (9, 5, 'Agent', 16186);
INSERT INTO `ao_professions` (`aoProfID`, `aoDBProfID`, `aoProf`, `aoIconID`) VALUES (10, 4, 'Fixer', 16300);
INSERT INTO `ao_professions` (`aoProfID`, `aoDBProfID`, `aoProf`, `aoIconID`) VALUES (11, 3, 'Engineer', 287091);
INSERT INTO `ao_professions` (`aoProfID`, `aoDBProfID`, `aoProf`, `aoIconID`) VALUES (12, 2, 'Martial Artist', 301439);
INSERT INTO `ao_professions` (`aoProfID`, `aoDBProfID`, `aoProf`, `aoIconID`) VALUES (13, 8, 'Bureaucrat', 293898);
INSERT INTO `ao_professions` (`aoProfID`, `aoDBProfID`, `aoProf`, `aoIconID`) VALUES (14, 10, 'Doctor', 44235);
