INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (1, 'Pharmaceuticals', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (2, 'Chemistry', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (3, 'Sense', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (4, 'Agility', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (5, 'Projectile AC', 'Y', 4, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (6, 'Melee AC', 'Y', 4, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (7, 'Energy AC', 'Y', 4, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (8, 'Chemical AC', 'Y', 4, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (9, 'Radiation AC', 'Y', 4, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (10, 'Cold AC', 'Y', 4, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (11, 'Fire AC', 'Y', 4, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (12, 'Poison AC', 'Y', 4, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (13, 'Max health', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (14, 'Aggressiveness', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (15, 'Scale', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (16, 'Perception', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (17, 'Run speed', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (18, 'Health', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (19, '1h Blunt', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (20, 'Aimed shot', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (21, 'Bow special attack', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (22, 'Burst', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (23, 'Fling shot', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (24, 'Full auto', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (25, 'Sharp objects', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (26, 'Bow', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (27, 'Assault rifle', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (28, 'Intelligence', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (29, 'Psychic', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (30, 'Stamina', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (31, 'Strength', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (32, 'Biological metamorphosis', 'Y', 1, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (33, 'Matter metamorphosis', 'Y', 1, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (34, 'Matter creation', 'Y', 1, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (35, 'Time and space', 'Y', 1, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (36, 'Psychological modifications', 'Y', 1, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (37, 'Sensory improvement', 'Y', 1, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (38, 'Current nano', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (39, 'Brawl', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (40, 'Dimach', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (41, 'Fast attack', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (42, 'Parry', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (43, 'Riposte', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (44, 'Sneak attack', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (45, 'Breaking and entry', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (46, 'Adventuring', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (47, 'Melee energy', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (48, 'Computer literacy', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (49, 'Concealment', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (50, 'Trap disarming', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (51, 'Electrical engineering', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (52, 'Piercing', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (53, 'Ranged energy', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (54, 'Quantum physics', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (55, 'First aid', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (56, 'Heavy weapons', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (57, 'Treatment', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (58, 'Evade close', 'Y', 2, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (59, 'Dodge ranged', 'Y', 2, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (60, 'Duck explosives', 'Y', 2, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (61, 'Grenade', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (62, '1h Edged', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (63, '2h Edged', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (64, '2h Blunt', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (65, 'Martial arts', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (66, 'Multi melee', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (67, 'Pistol', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (68, 'Smg', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (69, 'Mechanical engineering', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (70, 'Nano programming', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (71, 'Nano delta', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (72, 'Rifle', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (73, 'Shotgun', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (74, 'Attribute 0xa9', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (75, 'Psychology', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (76, 'Heal delta', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (77, 'Tutoring', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (78, 'Projectile damage modifier', 'Y', 3, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (79, 'Melee damage modifier', 'Y', 3, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (80, 'Energy damage modifier', 'Y', 3, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (81, 'Chemical damage modifier', 'Y', 3, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (82, 'Radiation damage modifier', 'Y', 3, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (83, 'Cold damage modifier', 'Y', 3, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (84, 'Poison damage modifier', 'Y', 3, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (85, 'Fire damage modifier', 'Y', 3, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (86, 'Weapon smithing', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (87, 'Nano init', 'Y', 5, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (88, 'Nano resist', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (89, 'Max nano', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (90, 'Melee init', 'Y', 5, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (91, 'Physical init', 'Y', 5, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (92, '339', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (93, 'Ranged init', 'Y', 5, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (94, 'Offense modifier', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (95, 'Nano cost modifier', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (96, 'Shield projectile damage', 'Y', 6, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (97, 'Shield melee damage', 'Y', 6, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (98, 'Shield energy damage', 'Y', 6, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (99, 'Shield chemical damage', 'Y', 6, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (100, 'Shield radiation damage', 'Y', 6, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (101, 'Shield cold damage', 'Y', 6, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (102, 'Shield fire damage', 'Y', 6, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (103, 'Shield poison damage', 'Y', 6, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (104, 'Defense modifier', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (105, 'Skill lock modifier', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (106, 'Critical decrease', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (107, '487', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (108, '469', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (109, '486', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (110, '468', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (111, '485', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (112, 'SL zone protection', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (113, '512', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (114, 'Credits', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (115, '180', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (116, 'Visual profession', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (117, 'Absorb projectile damage', 'Y', 7, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (118, 'Absorb melee damage', 'Y', 7, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (119, 'Absorb chemical damage', 'Y', 7, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (120, 'Absorb fire damage', 'Y', 7, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (121, 'Absorb energy damage', 'Y', 7, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (122, 'Absorb cold damage', 'Y', 7, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (123, 'Absorb poison damage', 'Y', 7, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (124, 'Absorb radiation damage', 'Y', 7, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (125, 'Reflect projectile damage', 'Y', 8, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (126, 'Reflect melee damage', 'Y', 8, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (127, 'Reflect energy damage', 'Y', 8, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (128, 'Reflect chemical damage', 'Y', 8, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (129, 'Reflect radiation damage', 'Y', 8, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (130, 'Reflect cold damage', 'Y', 8, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (131, 'Reflect fire damage', 'Y', 8, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (132, 'Reflect poison damage', 'Y', 8, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (133, 'Maximum projectile reflect', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (134, 'Maximum melee reflect', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (135, 'Maximum energy reflect', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (136, 'Maximum chemical reflect', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (137, 'Maximum radiation reflect', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (138, 'Maximum cold reflect', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (139, 'Maximum fire reflect', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (140, 'Maximum poison reflect', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (141, '689', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (142, 'Nano strain 145', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (143, 'Nano strain 146', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (144, 'Critical chance', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (145, 'Experience modifier', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (146, 'Nano range', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (147, 'Nano interrupt chance', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (148, 'Agg/Def', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (149, 'Experience recovery', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (150, 'Multi ranged', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (151, 'NCU memory', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (152, 'Nano strain 202', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (153, 'Form', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (154, 'Nano strain 282', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (155, 'Absorb special attacks', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (156, 'Nano strain 135', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (157, 'Nano strain 136', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (158, 'Nano strain 147', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (159, 'Nano strain 144', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (160, 'Nano strain 149', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (161, 'Proc initiative 2', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (162, 'Proc chance 2', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (163, 'Proc nano 2', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (164, '516', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (165, 'Nano attack damage modifier', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (166, 'Nano strain 256', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (167, 'Nano strain 705', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (168, 'Nano strain 707', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (169, 'Nano strain 703', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (170, 'Nano strain 710', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (171, 'Attack modifier', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (172, '454', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (173, '465', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (174, 'Heal modifier', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (175, 'Nano pool', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (176, 'Nano damage modifier', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (177, 'Proc initiative 1', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (178, 'Proc chance 1', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (179, 'Proc nano 1', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (180, 'Heal interval', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (181, '363', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (182, 'Nano vulnerability', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (183, 'Level', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (184, 'Experience regain percentage', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (185, 'Features', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (186, 'Weapon range', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (187, '407', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (188, 'Shield nano damage', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (189, 'Nano strain 795', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (190, 'Clan tokens', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (191, '659', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (192, '661', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (193, '39', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (194, '35', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (195, 'Nano strain 582', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (196, 'Nano strain 7', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (197, 'Nano strain 9', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (198, 'Nano strain 12', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (199, 'Nano strain 255', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (200, 'In battle', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (201, 'Nano strain 883', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (202, 'Reflect nano damage', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (203, 'Nano strain 833', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (204, 'Nano strain 834', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (205, 'Nano strain 679', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (206, 'Nano strain 891', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (207, 'Nano strain 892', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (208, 'Nano strain 186', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (209, 'Nano strain 1003', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (210, 'Nano strain 187', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (211, 'Nano strain 659', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (212, 'Nano strain 239', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (213, 'Nano strain 643', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (214, 'Nano strain 13', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (215, 'Map upgrades', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (216, 'Maximum nano reflect', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (217, 'Experience', 'N', NULL, 500);
INSERT INTO `mod_attribute_master` (`modAttributeID`, `modAttribute`, `canCombine`, `skillCombineID`, `sortOrder`) VALUES (218, '682', 'N', NULL, 500);
