INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (1, 'No longer drops', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (2, 'Arete Nano Container', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (3, 'APF Tradeskill', 'https://www.ao-universe.com/guides/alien-invasion/tradeskill-guides-3/general-crafting-2/apf-nano-guide');
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (4, 'RK Mob', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (5, 'Mission Reward', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (6, 'RK Dyna', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (7, 'RK Store', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (8, 'OFAB Store', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (9, 'Bronto Burger Quest', 'https://www.ao-universe.com/guides/classic-ao/quests-guides-3/corporal-ashley-winstead');
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (10, 'Dust Brigade Quest Part I', 'https://www.ao-universe.com/guides/classic-ao/quests-guides-3/dust-brigade-peacekeeper-constad');
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (11, 'Dust Brigade Quest Part II', 'https://www.ao-universe.com/guides/classic-ao/quests-guides-3/dust-brigade-peacekeeper-constad');
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (12, 'Pandemonium Garden', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (13, 'Inferno Sanctuary / Pandemonium Garden', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (14, 'Inferno Garden', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (15, 'Penumbra Sanctuary', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (16, 'Pen Xan Quest', 'https://www.ao-universe.com/guides/shadowlands/quests-guides-2/penumbra/xan-civilization-quest');
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (17, 'Adonis Garden', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (18, 'Elysium Garden', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (19, 'Penumbra Garden', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (20, 'Scheol Garden', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (21, 'Adonis Sanctuary', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (22, 'Elysium Sanctuary', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (23, 'Dust Brigade Quest Part V', 'https://www.ao-universe.com/guides/classic-ao/quests-guides-3/dust-brigade-peacekeeper-constad');
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (24, 'Dust Brigade Quest Part IV', 'https://www.ao-universe.com/guides/classic-ao/quests-guides-3/dust-brigade-peacekeeper-constad');
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (25, 'Scheol Yuttos Quest', 'https://www.ao-universe.com/guides/shadowlands/quests-guides-2/scheol/knowledge-of-the-yuttos');
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (26, 'Scheol Scientists Quest', 'https://www.ao-universe.com/guides/shadowlands/quests-guides-2/scheol/jobe-scientists');
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (27, 'Item Shop/Store', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (28, 'Arete Quest Reward', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (29, 'Orbital Appartment', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (30, 'Birthday Present', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (31, 'Greedy Shade / Pen Xan Quest', 'https://www.ao-universe.com/guides/shadowlands/quests-guides-2/penumbra/xan-civilization-quest');
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (32, 'SL Static (as Shadow Crystal)', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (33, 'Inner Sanctum Loot', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (34, 'Temple of the Three Winds Loot', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (35, 'Biodome Tradeskill', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (36, 'Ljotur the Lunatic / Polymorphed Lunatic', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (37, 'Elysium Garden (Not always) / SL Mob', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (38, 'Scheol Sanctuary', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (39, 'Nascense Garden', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (40, 'RK Store / Elysium Garden', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (41, 'Nascense Garden / Elysium Garden', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (42, 'Clan Starter Quest', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (43, 'Dust Brigade Quest Part III', 'https://www.ao-universe.com/guides/classic-ao/quests-guides-3/dust-brigade-peacekeeper-constad');
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (44, 'Greedy Shade / SL Static', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (45, 'SL Mob', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (46, 'Greedy Shade / Inferno Anansi Quest', 'https://www.ao-universe.com/guides/shadowlands/quests-guides-2/inferno/the-anansi');
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (47, 'Greedy Shade / Scheol Scientists Quest', 'https://www.ao-universe.com/guides/shadowlands/quests-guides-2/scheol/jobe-scientists');
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (48, 'Greedy Shade / Scheol Yuttos Quest', 'https://www.ao-universe.com/guides/shadowlands/quests-guides-2/scheol/knowledge-of-the-yuttos');
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (49, 'Lord Ghasap', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (50, 'Hezak the Immortal', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (51, 'Adonis Garden / RK Dyna', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (52, 'Inferno Tours Quest', 'https://www.ao-universe.com/guides/shadowlands/quests-guides-2/inferno/inferno-tours');
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (53, 'Fixer Grid Quest Part II', 'https://www.ao-universe.com/guides/classic-ao/quests-guides-3/fixer-grid-quest-part-2');
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (54, 'Fixer Grid Quest Part I', 'https://www.ao-universe.com/guides/classic-ao/quests-guides-3/fixer-grid-quest-part-1');
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (55, 'Inferno Garden / Inferno Sanctuary', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (56, 'The Pest', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (57, 'Special Agent Lamb', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (58, 'Ljotur the Lunatic', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (59, 'Starter equipment', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (60, 'Inferno Anansi Quest', 'https://www.ao-universe.com/guides/shadowlands/quests-guides-2/inferno/the-anansi');
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (61, 'Mission Reward / Inferno Garden', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (62, 'Mission Reward / Penumbra Garden', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (63, 'Leets-R-Us (Tower Shop)', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (64, 'SL Loot', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (65, 'Penumbra Garden / Penumbra Sanctuary', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (66, 'Adonis Garden / Adonis Sanctuary', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (67, 'Adonis Sanctuary / RK Dyna', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (68, 'Adonis Sanctuary / Penumbra Garden', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (69, 'Elysium Sanctuary / RK Dyna', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (70, 'Elysium Garden / RK Dyna', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (71, 'RK Store / Nascense Garden', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (72, 'Veteran Terminal (Tower Shop)', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (73, 'Item Shop', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (74, 'Item Shop/Event', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (75, 'RK Store / Scheol Sanctuary', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (76, 'RK Store / Scheol Garden', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (77, 'RK Store / Adonis Garden', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (78, 'RK Store / Elysium Sanctuary', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (79, 'Inferno Sanctuary', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (80, 'Obediency Enforcer', 'https://www.ao-universe.com/guides/classic-ao/encounter-guides-3/high-level-encounter-2/obediency-enforcer');
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (81, 'Christmas Event', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (82, 'Birthday Event', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (83, 'Item Shop/Halloween Event', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (84, 'Item Shop/Birthday Event', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (85, 'Halloween Event', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (86, 'Enigma Dogs Daily', 'https://www.ao-universe.com/guides/classic-ao/daily-missions-2/enigma-dogs');
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (87, 'Item Shop (Subscription reward)', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (88, 'Biodome', 'https://www.ao-universe.com/guides/classic-ao/encounter-guides-3/high-level-encounter-2/abandoned-facilities-biodomes');
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (89, 'Trader Pets Quest', 'https://www.ao-universe.com/guides/shadowlands/professions-guides/trader-pets');
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (90, 'Elysium Sanctuary / Pandemonium Garden', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (91, 'Omni Starter Quest', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (92, 'RK Store / Adonis Sanctuary', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (93, 'RK Store / Elysium Garden / Elysium Sanctuary', NULL);
INSERT INTO `nanos_locations` (`nanosLocationID`, `nanosLocation`, `questLink`) VALUES (94, 'Legacy Nano', NULL);
