INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (1, 'Buffs - Melee');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (2, 'Buffs');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (3, 'Creation');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (4, 'Debuffs - Melee');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (5, 'Orphans');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (6, 'Debuffs');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (7, 'Anti Crowd Control');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (8, 'Pet Buffs');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (9, 'Buffs - Attributes');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (10, 'Debuffs - Attributes');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (11, 'Buffs - Ranged Special');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (12, 'Debuffs - Ranged Special');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (13, 'Vehices');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (14, 'Nukes');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (15, 'Crowd Control');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (16, 'Buffs - Ranged');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (17, 'Debuffs - Ranged');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (18, 'Pet');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (19, 'Pet Combat');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (20, 'Combat');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (21, 'Buffs - Nano');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (22, 'Debuffs - Nano');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (23, 'Buffs - Melee Special');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (24, 'Debuffs - Melee Special');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (25, 'Buffs - Tradeskill Special');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (26, 'Buffs - Tradeskill');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (27, 'Buffs - Medical');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (28, 'Buffs - Utility');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (29, 'Buffs: Tradeskills');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (30, 'Protection');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (31, 'Drain');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (32, 'False Professions');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (33, 'PvP');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (34, 'Teleport');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (35, 'Transfer');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (36, 'Morphs');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (37, 'Pets');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (38, 'General');
INSERT INTO `nanos_schools` (`nanosSchoolID`, `nanosSchool`) VALUES (39, 'Proc');
