INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (1, '1H Blunt Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (2, '1H Edged Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (3, '1H Edged Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (4, '1Hand Blunt Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (5, '2H Blunt Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (6, '2H Blunt Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (7, '2H Edged Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (8, '2H Edged Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (9, 'AAD Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (10, 'AAO Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (11, 'AAO Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (12, 'Absorb AC Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (13, 'Adventurer Morph Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (14, 'Agent Direct Damage');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (15, 'Agent Escape Nanos');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (16, 'Agent Proc Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (17, 'Aggressive Construct Empowerment');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (18, 'Agility Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (19, 'Agility Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (20, 'Aimed Shot Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (21, 'Aimed Shot Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (22, 'AOE Taunt DOT');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (23, 'Armor Buff');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (24, 'Assault Rifle Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (25, 'Assault Rifle Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (26, 'Beacon Warp');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (27, 'Biological Metamorphosis Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (28, 'BioMet Buff');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (29, 'BioMet Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (30, 'Bow Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (31, 'Bow Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (32, 'Bow Special Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (33, 'Bow Special Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (34, 'Brawl Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (35, 'Brawl Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (36, 'Break & Entry Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (37, 'Break Entry Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (38, 'Breaking & Entry/Disarm Traps Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (39, 'Burst Buff');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (40, 'Burst Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (41, 'Challenger');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (42, 'Charm Other');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (43, 'Chemistry Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (44, 'Chemistry/Pharm Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (45, 'Climb Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (46, 'Complete Healing Line');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (47, 'Computer Literacy Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (48, 'Concealment Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (49, 'Concentration Critical Line');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (50, 'Controlled Destruction Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (51, 'Controlled Rage Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (52, 'Critical Decrease Buff');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (53, 'Critical Increase Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (54, 'Damage Buffs - Line A');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (55, 'Damage Buffs - Line C');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (56, 'Damage Change Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (57, 'Damage Drain');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (58, 'Damage Shield Upgrades');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (59, 'Damage Shields');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (60, 'Damage to Nano');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (61, 'Damage To Pet');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (62, 'Deflect Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (63, 'Deflect Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (64, 'Demotivational Speeches');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (65, 'DeTaunt');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (66, 'Dimach Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (67, 'Dimach Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (68, 'Disarm Trap Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (69, 'Disarm Traps Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (70, 'Doctor HP Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (71, 'Doctor Short HP Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (72, 'DOT - Line A');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (73, 'DOT - Line B');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (74, 'DOT Agent Strain A');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (75, 'DOT Nanotechnician Strain A');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (76, 'DOT Nanotechnician Strain B');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (77, 'DOT Removal');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (78, 'DOT Strain C');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (79, 'Drain Heal');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (80, 'Electrical Engineering Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (81, 'Energy Melee Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (82, 'Energy Melee Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (83, 'Enforcer Melee Energy Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (84, 'Enforcer Piercing Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (85, 'Enforcer Taunt Procs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (86, 'Engineer Auras');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (87, 'Engineer Debuffs Auras');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (88, 'Engineer Miniaturization');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (89, 'Engineer Pet AOE Snare Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (90, 'Engineer Special Attack Absorber');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (91, 'Evasion Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (92, 'Evasion Debuffs (Agent)');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (93, 'Executioner Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (94, 'Experience Constructs - XP Bonus');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (95, 'False Profession');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (96, 'Fast Attack Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (97, 'Fast Attack Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (98, 'Fear');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (99, 'Fear - PVP');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (100, 'Fear - PvP (Reduce)');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (101, 'Field Quantum Physics Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (102, 'First Aid And Treatment Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (103, 'First Aid Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (104, 'Fixer Dodge Buffs Line');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (105, 'Fixer Fear Immunity');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (106, 'Fixer Long Heal Over Time');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (107, 'Fixer NCU Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (108, 'Fixer Short Heal Over Time');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (109, 'Fixer Suppressor Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (110, 'Fling Shot Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (111, 'Fling Shot Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (112, 'Fortify');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (113, 'Full Auto Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (114, 'Full Auto Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (115, 'Fury');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (116, 'General Chemical AC Debuff');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (117, 'General Cold AC Debuff');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (118, 'General Projectile AC Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (119, 'General Psychic Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (120, 'General Radiation AC Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (121, 'Grenade Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (122, 'Grenade Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (123, 'Halo Nano Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (124, 'Heal Delta Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (125, 'Heal Over Time');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (126, 'Healing Construct Empowerment');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (127, 'Health and Nano Over Time Drain');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (128, 'Health Drain');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (129, 'Heavy Weapons Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (130, 'HP Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (131, 'HP Regeneration');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (132, 'Initiative Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (133, 'Initiative Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (134, 'Intelligence Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (135, 'Intelligence Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (136, 'Interrupt Modifier');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (137, 'Keeper Aura-Absorb/Reflect/AMS Buff');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (138, 'Keeper Aura-Damage/Snare Reduction Buff');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (139, 'Keeper Aura-HP and NP Heal');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (140, 'Keeper Deflect/Riposte Buff');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (141, 'Keeper Evade/Dodge/Duck Buff');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (142, 'Keeper Fear Immunity');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (143, 'Keeper Proc Buff');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (144, 'Keeper Str/Stam/Agi Buff');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (145, 'Knife Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (146, 'Knife Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (147, 'Leet Empower');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (148, 'LR Energy Weapon Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (149, 'LR Energy Weapon Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (150, 'Major Evasion Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (151, 'Martial Artist Bow Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (152, 'Martial Artist Zazen Stance');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (153, 'Martial Arts Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (154, 'Martial Arts Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (155, 'MatCrea Buff');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (156, 'MatCrea Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (157, 'Material Metamorphosis Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (158, 'TimeSpace Buff');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (159, 'MatLoc Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (160, 'MatMet Buff');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (161, 'MatMet Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (162, 'Matter Creation Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (163, 'Max Health Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (164, 'Crowd Control');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (165, 'Mechanical Engineering Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (166, 'Melee Weapon Buffs Line');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (167, 'Mesmerization Construct Empowerment');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (168, 'Meta-Physicist Damage Debuffs - Line A');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (169, 'Meta-Physicist Damage Debuffs - Line B');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (170, 'Meta-Physicist Initiatives/Damage Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (171, 'Metaphysicist Mind Damage Nano Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (172, 'Mezz');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (173, 'Mongo Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (174, 'Morph Heal');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (175, 'Motivational SpeechEffect');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (176, 'MP Attack Pet Damage Type');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (177, 'MP Pet Damage Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (178, 'MP Pet Initiative Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (179, 'Multiwield Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (180, 'Nano Damage Multiplier Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (181, 'Nano Delta Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (182, 'Nano Delta Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (183, 'Nano Drain - Line A');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (184, 'Nano Drain - Line B');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (185, 'Nano Over Time - Line A');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (186, 'Nano Point Heals');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (187, 'Nano Programming Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (188, 'Nano Resist Buffs ');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (189, 'Nano Resistance Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (190, 'Nano Resistance Debuffs - Line A');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (191, 'Nano Shutdown Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (192, 'Nemesis');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (193, 'Nemesis Nano Programs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (194, 'NF Range Buff');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (195, 'NP Buff');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (196, 'NP Cost Buff');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (197, 'NP Regeneration');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (198, 'Nullity Sphere Nano');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (199, 'Orphan - NO STACKING');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (200, 'Other Root/Snare Resist Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (201, 'Perception Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (202, 'Pet Damage Over Time Resist Nanos');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (203, 'Pet Defensive Nanos');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (204, 'Pet Heal Delta');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (205, 'Pet Short Term Damage Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (206, 'Pet Snare/Root Resistance Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (207, 'Pet Taunt Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (208, 'Pharmaceutical Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (209, 'Pharmaceuticals Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (210, 'Piercing Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (211, 'Piercing Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (212, 'Pisto Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (213, 'Pistol Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (214, 'Polymorph');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (215, 'Proximity Range Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (216, 'Psy/Int Buff');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (217, 'Psychic Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (218, 'Psychic Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (219, 'Psychology Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (220, 'PsyMod Buff');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (221, 'PsyMod Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (222, 'Radiation AC Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (223, 'Rage');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (224, 'Ranged Energy Weapon Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (225, 'Ransack/Deprive Resist Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (226, 'Reflect Shield');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (227, 'Resurrection Sickness Removal');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (228, 'Reverse Knockback');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (229, 'Rifle Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (230, 'Rifle Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (231, 'Riposte Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (232, 'Riposte Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (233, 'Root');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (234, 'Root Reduction');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (235, 'Runspeed Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (236, 'Self Root/Snare Resist Buff');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (237, 'Self Root/Snare Resist Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (238, 'Sense Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (239, 'Sense Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (240, 'SenseImp Buff');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (241, 'SenseImp Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (242, 'Sensory Improvement Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (243, 'Shade Piercing Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (244, 'Shade Proc Buff');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (245, 'Shadowland Bind and Recall');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (246, 'Shadowlands Bind and Recall');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (247, 'Shadowlands Maps');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (248, 'Shield of the Obedient Servant');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (249, 'Shotgun Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (250, 'Shotgun Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (251, 'Single Target Healing');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (252, 'Siphon Box');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (253, 'Skill Lock Modifier Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (254, 'SL Nanopoint Drain');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (255, 'SMG Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (256, 'SMG Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (257, 'Snare');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (258, 'Sneak Attack Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (259, 'Sneak Attack Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (260, 'Social Pets');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (261, 'Soldier Full Auto Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (262, 'Soldier Shotgun Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (263, 'Special Attack Absorber');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (264, 'Stamina Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (265, 'Stamina Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (266, 'Strength Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (267, 'Strength Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (268, 'Stun');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (269, 'Summon Item');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (270, 'Support Pets');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (271, 'Taunt');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (272, 'Team Healing');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (273, 'Thrown Grappling Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (274, 'Thrown Grappling Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (275, 'Time and Space Debuffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (276, 'Total Focus');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (277, 'Trader AAD Drain');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (278, 'Trader AAO Drain');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (279, 'Trader AC Transfer Target Buff (Redeem)');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (280, 'Trader AC Transfer Target Debuff (Draw)');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (281, 'Trader AC Transfer Target Debuff (Siphon)');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (282, 'Trader Shudown Skill Buff');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (283, 'Trader Shudown Skill Debuff');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (284, 'Trader Skill Transfer Target Debuff (Deprive)');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (285, 'Trader Skill Transfer Target Debuff (Ransack)');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (286, 'Treatment Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (287, 'True Profession');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (288, 'Tutoring Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (289, 'Weapon Effect Add-On 2');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (290, 'Weapon Smithing Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (291, '1H Blunt Weapons');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (292, '2H Blunt Weapons');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (293, 'AC');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (294, 'Air');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (295, 'Ammo');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (296, 'AoE Nuke');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (297, 'Armor');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (298, 'Attack Pet');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (299, 'Attack Pet Crystalizer');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (300, 'Attack Pet Summon');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (301, 'AuraCancellation');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (302, 'Boon Crystals');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (303, 'Composite');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (304, 'Composite Nano Buffs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (305, 'Corporate Leadership');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (306, 'Damage');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (307, 'Debuff NanoAC Heavy');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (308, 'Emergency Sneak');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (309, 'Evasion');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (310, 'Fixer Grid');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (311, 'General');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (312, 'General Nuke');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (313, 'Give Energy');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (314, 'Give Life');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (315, 'Grid Armor');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (316, 'Grid Warp');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (317, 'Heal');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (318, 'Heal Pet');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (319, 'Health');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (320, 'Hostile NCU Duration Reduction');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (321, 'Hostile NCU Wipe');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (322, 'Land');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (323, 'Leet Charm');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (324, 'Melee Weapon');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (325, 'Mezz Pet');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (326, 'Nano Heal');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (327, 'Nano Resistance Debuff (Line A)');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (328, 'NO STACKING');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (329, 'Normal');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (330, 'Notum Wars');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (331, 'Nuke');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (332, 'Nuke Normal');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (333, 'Orphan');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (334, 'Other Root Reduction');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (335, 'Other Snare Reduction');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (336, 'Pet Heal');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (337, 'Pet Reduction');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (338, 'Pet Root/Snare Reduction');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (339, 'Pet Warp');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (340, 'Proc: Masters Bidding');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (341, 'Ranged Weapon');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (342, 'Reflect');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (343, 'Robot');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (344, 'Robotic Dogs');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (345, 'Robots');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (346, 'Root Duration Reduction');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (347, 'Root Removal');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (348, 'RootSnareReduction');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (349, 'Self');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (350, 'Self Grid');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (351, 'Self Root Reduction');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (352, 'Self Root Removal');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (353, 'Self Snare Reduction');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (354, 'Self Snare Removal');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (355, 'Service Tower');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (356, 'Shadowlands');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (357, 'Shadowlands Garden Warp');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (358, 'Shadowlands Tap Notum Vein');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (359, 'ShadowWeb Spinner');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (360, 'Shield Weapons');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (361, 'Snare Removal');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (362, 'Snowball');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (363, 'Special');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (364, 'Spirit Drain');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (365, 'Target Healing');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (366, 'Target Snare Removal');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (367, 'Taunt (normal)');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (368, 'Taunt (temporary)');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (369, 'Taunt Target');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (370, 'Team');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (371, 'Team Grid');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (372, 'Teleport');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (373, 'Transference');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (374, 'Umbral Wrangler');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (375, 'Wrangle');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (376, 'L33t');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (377, 'Pit Lizard');
INSERT INTO `nanos_strains` (`nanosStrainID`, `nanosStrain`) VALUES (378, 'Agent Damage Proc-DamageInflictSegment');
