INSERT INTO `nanos_professions` (`nanosProfID`, `nanosProf`) VALUES (1, 'General');
INSERT INTO `nanos_professions` (`nanosProfID`, `nanosProf`) VALUES (2, 'Enforcer');
INSERT INTO `nanos_professions` (`nanosProfID`, `nanosProf`) VALUES (3, 'Meta-Physicist');
INSERT INTO `nanos_professions` (`nanosProfID`, `nanosProf`) VALUES (4, 'Adventurer');
INSERT INTO `nanos_professions` (`nanosProfID`, `nanosProf`) VALUES (5, 'Keeper');
INSERT INTO `nanos_professions` (`nanosProfID`, `nanosProf`) VALUES (6, 'Shade');
INSERT INTO `nanos_professions` (`nanosProfID`, `nanosProf`) VALUES (7, 'Soldier');
INSERT INTO `nanos_professions` (`nanosProfID`, `nanosProf`) VALUES (8, 'Nano-Technician');
INSERT INTO `nanos_professions` (`nanosProfID`, `nanosProf`) VALUES (9, 'Trader');
INSERT INTO `nanos_professions` (`nanosProfID`, `nanosProf`) VALUES (10, 'Agent');
INSERT INTO `nanos_professions` (`nanosProfID`, `nanosProf`) VALUES (11, 'Fixer');
INSERT INTO `nanos_professions` (`nanosProfID`, `nanosProf`) VALUES (12, 'Engineer');
INSERT INTO `nanos_professions` (`nanosProfID`, `nanosProf`) VALUES (13, 'Martial Artist');
INSERT INTO `nanos_professions` (`nanosProfID`, `nanosProf`) VALUES (14, 'Bureaucrat');
INSERT INTO `nanos_professions` (`nanosProfID`, `nanosProf`) VALUES (15, 'Doctor');
INSERT INTO `nanos_professions` (`nanosProfID`, `nanosProf`) VALUES (16, 'Agent:Fixer:Soldier');
INSERT INTO `nanos_professions` (`nanosProfID`, `nanosProf`) VALUES (17, 'Enforcer:Keeper:Martial Artist:Shade');
INSERT INTO `nanos_professions` (`nanosProfID`, `nanosProf`) VALUES (18, 'Bureaucrat:Engineer:Meta-Physicist');
INSERT INTO `nanos_professions` (`nanosProfID`, `nanosProf`) VALUES (19, 'Meta-Physicist:Nano-Technician');
INSERT INTO `nanos_professions` (`nanosProfID`, `nanosProf`) VALUES (20, 'Bureaucrat:Doctor:Engineer:Meta-Physicist:Soldier');
INSERT INTO `nanos_professions` (`nanosProfID`, `nanosProf`) VALUES (21, 'Bureaucrat:Meta-Physicist:Nano-Technician');
INSERT INTO `nanos_professions` (`nanosProfID`, `nanosProf`) VALUES (22, 'Enforcer:Keeper:Shade:Soldier');
INSERT INTO `nanos_professions` (`nanosProfID`, `nanosProf`) VALUES (23, 'Adventurer:Keeper:Shade');
