INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (1, '180', 0);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (2, '1h Blunt', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (3, '1h Edged', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (4, '2h Blunt', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (5, '2h Edged', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (6, '35', 0);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (7, '363', 0);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (8, '39', 0);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (9, '659', 0);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (10, '661', 0);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (11, '689', 0);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (12, 'Absorb chemical damage', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (13, 'Absorb cold damage', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (14, 'Absorb energy damage', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (15, 'Absorb fire damage', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (16, 'Absorb melee damage', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (17, 'Absorb poison damage', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (18, 'Absorb projectile damage', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (19, 'Absorb radiation damage', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (20, 'Adventuring', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (21, 'Agg/Def', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (22, 'Aggressiveness', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (23, 'Agility', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (24, 'Aimed shot', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (25, 'Assault rifle', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (26, 'Attack modifier', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (27, 'Attribute 0xa9', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (28, 'Belt decks', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (29, 'Biological metamorphosis', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (30, 'Body development', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (31, 'Bow', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (32, 'Bow special attack', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (33, 'Brawl', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (34, 'Breaking and entry', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (35, 'Burst', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (36, 'Chemical AC', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (37, 'Chemical damage modifier', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (38, 'Chemistry', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (39, 'Cold AC', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (40, 'Cold damage modifier', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (41, 'Computer literacy', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (42, 'Concealment', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (43, 'Critical chance', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (44, 'Critical decrease', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (45, 'Current nano', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (46, 'Defense modifier', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (47, 'Dimach', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (48, 'Dodge ranged', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (49, 'Duck explosives', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (50, 'Electrical engineering', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (51, 'Energy', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (52, 'Energy AC', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (53, 'Energy damage modifier', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (54, 'Evade close', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (55, 'Experience modifier', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (56, 'Experience regain percentage', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (57, 'Fast attack', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (58, 'Fire AC', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (59, 'Fire damage modifier', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (60, 'First aid', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (61, 'Fling shot', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (62, 'Full auto', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (63, 'Grenade', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (64, 'Heal delta', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (65, 'Heal interval', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (66, 'Heal modifier', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (67, 'Health', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (68, 'Heavy weapons', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (69, 'In battle', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (70, 'Intelligence', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (71, 'Map navigation', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (72, 'Martial arts', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (73, 'Matter creation', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (74, 'Matter metamorphosis', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (75, 'Max health', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (76, 'Max nano', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (77, 'Maximum chemical reflect', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (78, 'Maximum cold reflect', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (79, 'Maximum energy reflect', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (80, 'Maximum fire reflect', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (81, 'Maximum melee reflect', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (82, 'Maximum nano reflect', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (83, 'Maximum poison reflect', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (84, 'Maximum projectile reflect', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (85, 'Maximum radiation reflect', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (86, 'Mechanical engineering', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (87, 'Melee AC', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (88, 'Melee damage modifier', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (89, 'Melee energy', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (90, 'Melee init', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (91, 'Multi melee', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (92, 'Multi ranged', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (93, 'Nano attack damage modifier', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (94, 'Nano cost modifier', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (95, 'Nano damage modifier', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (96, 'Nano delta', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (97, 'Nano init', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (98, 'Nano interrupt chance', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (99, 'Nano pool', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (100, 'Nano programming', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (101, 'Nano range', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (102, 'Nano resist', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (103, 'Nano vulnerability', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (104, 'NCU memory', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (105, 'Offense modifier', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (106, 'Organization upkeep', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (107, 'Parry', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (108, 'Perception', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (109, 'Pharmaceuticals', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (110, 'Physical init', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (111, 'Piercing', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (112, 'Pistol', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (113, 'Poison AC', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (114, 'Poison damage modifier', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (115, 'Projectile AC', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (116, 'Projectile damage modifier', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (117, 'Psychic', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (118, 'Psychological modifications', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (119, 'Psychology', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (120, 'Quantum physics', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (121, 'Radiation AC', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (122, 'Radiation damage modifier', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (123, 'Ranged energy', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (124, 'Ranged init', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (125, 'Reflect chemical damage', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (126, 'Reflect cold damage', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (127, 'Reflect energy damage', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (128, 'Reflect fire damage', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (129, 'Reflect melee damage', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (130, 'Reflect nano damage', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (131, 'Reflect poison damage', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (132, 'Reflect projectile damage', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (133, 'Reflect radiation damage', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (134, 'Reset points', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (135, 'Rifle', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (136, 'Riposte', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (137, 'Run speed', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (138, 'Scale', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (139, 'Sense', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (140, 'Sensory improvement', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (141, 'Shadow breed', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (142, 'Sharp objects', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (143, 'Shield chemical damage', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (144, 'Shield cold damage', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (145, 'Shield energy damage', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (146, 'Shield fire damage', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (147, 'Shield melee damage', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (148, 'Shield nano damage', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (149, 'Shield poison damage', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (150, 'Shield projectile damage', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (151, 'Shield radiation damage', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (152, 'Shotgun', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (153, 'Skill lock modifier', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (154, 'Smg', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (155, 'Sneak attack', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (156, 'Stamina', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (157, 'Strength', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (158, 'Swimming', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (159, 'Time and space', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (160, 'Trap disarming', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (161, 'Treatment', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (162, 'Tutoring', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (163, 'Vehicle air', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (164, 'Vehicle ground', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (165, 'Vehicle water', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (166, 'Weapon range', 1);
INSERT INTO `search_mod_att_effects` (`searchModAttID`, `modAttName`, `activeRecord`) VALUES (167, 'Weapon smithing', 1);
