INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (1, 'Max Health', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (16, 'Strength', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (17, 'Agility', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (18, 'Stamina', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (19, 'Intelligence', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (20, 'Sense', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (21, 'Psychic', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (22, 'Attack rating', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (35, 'Damage to Pet', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (39, 'Damage To Pet Damage Multiplier', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (45, 'Free deck slot', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (51, 'Aggdef', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (90, 'Imp/Proj AC', 'Projectile AC', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (91, 'Melee/ma AC', 'Melee/Martial Arts AC', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (92, 'Energy AC', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (93, 'Chemical AC', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (94, 'Radiation AC', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (95, 'Cold AC', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (96, 'Disease AC', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (97, 'Fire AC', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (100, 'Martial Arts', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (101, 'Mult. Melee', 'Multi Melee', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (102, '1h Blunt', '1 handed blunt', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (103, '1h Edged', '1 handed edged', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (104, 'Melee Ener.', 'Melee Energy', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (105, '2h Edged', '2 handed edged', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (106, 'Piercing', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (107, '2h Blunt', '2 handed blunt', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (108, 'Sharp Obj', 'Sharp Objects', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (109, 'Grenade', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (110, 'Heavy Weapons', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (111, 'Bow', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (112, 'Pistol', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (113, 'Rifle', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (114, 'MG / SMG', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (115, 'Shotgun', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (116, 'Assault Rif', 'Assault Rifle', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (117, 'Vehicle Water', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (118, 'Melee Init.', 'Melee Initiative', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (119, 'Ranged Init.', 'Ranged Initiative', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (120, 'Physical Init', 'Physical Initiative', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (121, 'Bow Spc Att', 'Bow Special Attack', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (122, 'Sensory Impr', 'Sensory Improvement', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (123, 'First Aid', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (124, 'Treatment', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (125, 'Mech. Engi', 'Mechanical Engineering', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (126, 'Elec. Engi', 'Electrical Engineering', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (127, 'Matt. Metam', 'Matter Metamorphosis', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (128, 'Bio Metamor', 'Biological Metamorphosis', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (129, 'Psycho Modi', 'Pychological Modifications', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (130, 'Matter Crea', 'Matter Creation', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (131, 'Time&Space', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (132, 'Nano Pool', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (133, 'Ranged Ener', 'Ranged Energy', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (134, 'Multi Ranged', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (135, 'Trap Disarm.', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (136, 'Perception', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (137, 'Adventuring', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (138, 'Swimming', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (139, 'Vehicle Air', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (141, 'Tutoring', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (142, 'Brawling', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (143, 'Riposte', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (144, 'Dimach', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (145, 'Deflect', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (146, 'Sneak Atck', 'Sneak Attack', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (147, 'Fast Attack', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (148, 'Burst', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (149, 'NanoC. Init.', 'Nano Cast Initiative', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (150, 'Fling Shot', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (151, 'Aimed Shot', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (152, 'Body Dev.', 'Body Development', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (153, 'Duck-Exp', 'Duck Explosives', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (154, 'Dodge-Rng', 'Dodge Range', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (155, 'Evade-ClsC', 'Evade Close Combat', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (156, 'Run Speed', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (157, 'Quantum FT', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (158, 'Weapon Smt', 'Weapon Smithing', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (159, 'Pharma Tech', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (160, 'Nano Progra', 'Nano Programming', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (161, 'Comp. Liter', 'Computer Literacy', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (162, 'Psychology', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (163, 'Chemistry', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (164, 'Concealment', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (165, 'Break&Entry', 'Breaking and Entering', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (166, 'Vehicle Ground', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (167, 'Full Auto', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (168, 'Nano Resist', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (180, 'Used NCU', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (181, 'Max NCU', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (201, 'Aggressiveness', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (205, 'ReflectProjectileAC', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (206, 'ReflectMeleeAC', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (207, 'ReflectEnergyAC', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (208, 'ReflectChemicalAC', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (216, 'ReflectRadiationAC', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (217, 'ReflectColdAC', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (218, 'ReflectNanoAC', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (219, 'ReflectFireAC', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (221, 'Max Nano', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (225, 'ReflectPoisonAC', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (226, 'ShieldProjectileAC', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (227, 'ShieldMeleeAC', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (228, 'ShieldEnergyAC', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (229, 'ShieldChemicalAC', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (230, 'ShieldRadiationAC', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (231, 'ShieldColdAC', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (232, 'ShieldNanoAC', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (233, 'ShieldFireAC', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (234, 'ShieldPoisonAC', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (276, 'Add All Off.', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (277, 'Add All Def.', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (278, 'Add. Proj. Dam.', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (279, 'Add. Melee Dam.', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (280, 'Add. Energy Dam.', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (281, 'Add. Chem. Dam.', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (282, 'Add. Rad. Dam.', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (311, 'Add. Cold Dam.', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (315, 'Add. Nano Dam.', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (316, 'Add. Fire Dam.', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (317, 'Add. Poison Dam.', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (318, '% Add. Nano Cost', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (319, '% Add. Xp', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (343, 'HealDelta', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (360, 'Scale', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (364, 'NanoDelta', 'Nano Delta', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (379, 'CriticalIncrease', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (380, 'RangeInc. Weapon', 'Ranged Increase Weapon', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (381, 'RangeInc. NF', 'Ranged Increase Nano', 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (382, 'SkillLockModifier', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (383, 'Decreased Nano-Interrupt Modifier %', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (391, 'Critical Decrease', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (475, 'MaxReflectedProjectileDmg', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (476, 'MaxReflectedMeleeDmg', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (477, 'MaxReflectedEnergyDmg', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (478, 'MaxReflectedChemicalDmg', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (479, 'MaxReflectedRadiationDmg', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (480, 'MaxReflectedColdDmg', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (481, 'MaxReflectedNanoDmg', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (482, 'MaxReflectedFireDmg', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (483, 'MaxReflectedPoisonDmg', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (535, 'Healing Efficiency', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (536, 'Direct Nano Damage Efficiency', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (593, 'Regain XP Percentage', NULL, 1);
INSERT INTO `skill_master_tbl` (`skillID`, `skillName`, `skillCommonName`, `activeRecord`) VALUES (689, 'Heal Reactivity', NULL, 1);
